version: 2
defaults: &defaults
  machine:
    image: circleci/classic:201708-01

  working_directory: ~/ussd_airflow

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: start the containers
          command: |
            docker-compose up -d
            sleep 10

      - run:
          name: Running tests
          command: |
            curl --retry 10 --retry-delay 5 -v http://localhost:8007
            docker-compose run app bash -c 'coverage run --omit=*test*,*ven* manage.py test && bash <(curl -s https://codecov.io/bash) && python-codacy-coverage -r coverage.xml'
  deploy:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: deploying
          command: |
            docker-compose run --no-deps -e PYPI_PASSWORD=$PYPI_PASSWORD -e PYPI_USER=$PYPI_USER -e VERSION=$CIRCLE_TAG app bash -c 'printf "[distutils]\nindex-servers = pypi \n[pypi]\nusername:$PYPI_USER\npassword:$PYPI_PASSWORD" > ~/.pypirc && python setup.py sdist upload'



workflows:
  version: 2
  ci:
    jobs:
      - test
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

